// Generated by Wrangler by running `wrangler types`

interface Env {
	POSTER_SLUG_TO_FILE: KVNamespace;
	OPENAI_API_KEY: string;
	SPOTIFY_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
	SPOTIFY_MAIN_USER_ID: string;
	PUBLIC_POSTER_HOST: string;
	ORCHESTRATOR: DurableObjectNamespace<import("./src/index").Orchestrator>;
	POSTER_AGENT: DurableObjectNamespace<import("./src/index").PosterAgent>;
	SPOTIFY_USER: DurableObjectNamespace<import("./src/index").SpotifyUser>;
	BAND_AID: R2Bucket;
	PLAYLISTER: Workflow;
}
